---
# tasks file for fileserver

- name: Verify File Server Role is installed.
  win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: True

- name: Ensure directory structure for public share exists
  win_file:
    path: "{{ share_path }}"
    state: directory

- name: Ensure public share exists
  win_share:
    name: public
    description: Basic RW share for all domain users
    path: "{{ share_path }}"
    list: yes
    full: "{{ share_full }}"
    change: "{{ share_rw }}"
