---
- name: set hostname
  win_hostname:
    name: "{{ inventory_hostname_short }}"
  register: res

- name: reboot server after change to hostname
  win_reboot:
    msg: "Changing hostname. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 120
  when: res.reboot_required

- name: Create Self Public IP Variable
  raw: "Resolve-DnsName -Name {{groups['primary_domain_controller'][0]}} -Type A -DnsOnly | select -expand IPAddress"
  register: windows_public_ip

- name: change DNS server
  when: not ansible_windows_domain_member
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ windows_public_ip.stdout_lines | join }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
    msg: "Joining AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 420
  when: domain_joined.reboot_required

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900

- name: install ad
  win_domain_controller:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ domain_safemode_password }}"
    state: domain_controller
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed

- name: Install AD client tools
  win_feature:
    name:
      - RSAT-AD-Tools
    state: present
