---
# tasks file for rdgserver
# Server is joined to domain
# Server is running on 2016
# Current user is a member of  group “Administrators”  (lusrmgr.msc  -> groups)
# PowerShell is configured to receive remote queries (Enable-PSRemoting)
# Remote Desktop Services are not forbidden in GPOs (default policies)
# Remote management is enabled in Server Manager (servermanager -> local server -> remote management)
# Firewall rules for remote management are enabled (Get-NetFirewallRule *winmgmt*|select name,enabled)
# There are no network and time synchronization issues between this server and my environment

- name: Install RD Licensing
  win_feature:
    name:
     - RDS-Licensing
    include_sub_features: yes
    include_management_tools: yes
    state: present

- name: Install RD connection broker
  win_feature:
    name:
     - RDS-Connection-Broker
    include_sub_features: yes
    include_management_tools: yes
    state: present

- name: Install RD gateway
  win_feature:
    name:
     - RDS-Gateway
    include_sub_features: yes
    include_management_tools: yes
    state: present

- name: Install RD Session Host
  win_feature:
    name:
     - RDS-RD-Server
    include_sub_features: yes
    include_management_tools: yes
    state: present
  register: win_feature

- name: Install remote server admin tools
  win_feature:
    name:
     - RSAT-RDS-Gateway
    include_sub_features: yes
    include_management_tools: yes
    state: present

- name: reboot to enable RDS services deployment
  win_reboot:
    msg: "Enable RDS services. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 120
  when: win_feature.reboot_required

- name: Copy RDGW pfx certificate
  win_copy:
    src: "{{ certs_local_folder }}/{{ rdg_pfx_file }}"
    dest: "{{ scripts_folder }}\\{{ rdg_pfx_file }}"

- name: Copy RDGW deployment scripts to server
  win_copy:
    src: "{{ role_path }}/files/"
    dest: "{{ scripts_folder }}\\"

- name: Create task to run a RDGW deployment PS script on boot
  win_scheduled_task:
    name: DeployRDGW
    description: Run a PowerShell script to deploy RD Gateway
    actions:
    - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Unrestricted -NonInteractive -Command "& 'C:\Scripts\Deploy-RDGW.ps1' -ServerFQDN {{ rdg_ext_fqdn }} -ConnectionBroker {{ inventory_hostname }} -SessionHost {{ inventory_hostname }} -PfxFilename {{ scripts_folder }}\{{rdg_pfx_file}} -PfxPassword {{ rdgpfxpassword }}"
      working_directory: C:\Scripts
    triggers:
    - type: boot
    username: SYSTEM
    run_level: highest
    state: present

- name: Run Scheduled Task for DeployRDGW
  win_shell: Start-ScheduledTask -TaskName "DeployRDGW"
  register: task_deploy_rdgw_result

- name: Collect DeployRDGW result
  debug:
    msg: "{{ task_deploy_rdgw_result }}"

- name: Create task to run a RDGW deployment PS script on boot
  win_scheduled_task:
    name: DeployRDGW
    enabled: no

# - name: Get information about a folder
#   win_scheduled_task_stat:
#     name: DeployRDGW
#   register: task_deploy_rdgw_stat

- name: Create a new RDS CAP with a 30 minutes timeout and clipboard redirection enabled
  win_rds_cap:
    name: Domain CAP
    auth_method: password
    user_groups:
      - 'dev\Domain Users'
    session_timeout: 30
    session_timeout_action: disconnect
    allow_only_sdrts_servers: yes
    redirect_clipboard: yes
    redirect_drives: yes
    redirect_printers: no
    redirect_serial: no
    redirect_pnp: no
    state: enabled
#  when: task_deploy_rdgw_stat.state.status=='TASK_STATE_READY'

- name: Create a new RDS RAP
  win_rds_rap:
    name: Domain RAP
    description: Allow all users to connect to any resource through ports 3389
    user_groups:
      - 'dev\Domain Users'
    computer_group_type: allow_any
    allowed_ports:
      - 3389
    state: enabled
