---
    # SQLSysAdminAccounts:
    #   - "{{ item.svcaccount }}"
    #   - "{{ inventory_hostname_short }}\\Administrators"
    #   - "{{ domain }}\\Domain Admins"

- name: Install SQL Server with product key
  win_dsc:
    resource_name: SqlSetup
    InstanceName: "{{ item.instance_name }}"
    Features: "{{ item.features }}"
    SQLCollation: "{{ item.instance_collation }}"
    SQLSvcAccount_username: "{{ item.svcaccount }}"
    SQLSvcAccount_password: "{{ item.svcpassword }}"
    SQLSysAdminAccounts: "{{ item.svcaccount }}"
    InstanceDir: "{{ item.instance_dir }}"
    InstallSQLDataDir: "{{ item.installdb_path }}"
    SQLUserDBDir: "{{ item.userldb_path }}"
    SQLUserDBLogDir: "{{ item.userdblog_path }}"
    SQLTempDBDir: "{{ item.tempdb_path }}"
    SQLTempDBLogDir: "{{ item.tempdblog_path }}"
    SQLBackupDir: "{{ item.backup_path }}"
    SourcePath: "{{ disk_image_out.results[0].mount_path }}"
    UpdateEnabled: False
    ForceReboot: False
    SecurityMode: SQL
    SAPwd_username: sa
    SAPwd_Password: "{{ item.svcpassword }}"
  loop: "{{ rl_mssql_instances }}"
  when: not item.productkey is defined
  register: sql_installed

- name: Install SQL Server without product key
  win_dsc:
    resource_name: SqlSetup
    InstanceName: "{{ item.instance_name }}"
    Features: SQLENGINE
    SQLCollation: "{{ item.instance_collation }}"
    SQLSvcAccount_username: "{{ item.svcaccount }}"
    SQLSvcAccount_password: "{{ item.svcpassword }}"
    SQLSysAdminAccounts: "{{ item.svcaccount }}"
    InstanceDir: "{{ item.instance_dir }}"
    InstallSQLDataDir: "{{ item.installdb_path }}"
    SQLUserDBDir: "{{ item.userldb_path }}"
    SQLUserDBLogDir: "{{ item.userdblog_path }}"
    SQLTempDBDir: "{{ item.tempdb_path }}"
    SQLTempDBLogDir: "{{ item.tempdblog_path }}"
    SQLBackupDir: "{{ item.backup_path }}"
    SourcePath: "{{ disk_image_out.results[0].mount_path }}"
    UpdateEnabled: False
    ForceReboot: False
    ProductKey: "{{ item.productkey }}"
  loop: "{{ rl_mssql_instances }}"
  when: item.productkey is defined
  register: sql_installed

- name: configure Firwall for SQL
  win_dsc:
    resource_name: SqlWindowsFirewall
    Features: SQLENGINE
    InstanceName: "{{ item.instance_name }}"
    Ensure: Present
    SourcePath: "{{ disk_image_out.results[0].mount_path }}"
  loop: "{{ rl_mssql_instances }}"

- name: reboot after SQL Server install
  win_reboot:
    msg: "SQL Server installed. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 180
  when: sql_installed
