---

- hosts: web_servers
  pre_tasks:

  - name: create Temp folder
    win_file:
      path: C:\Temp
      state: directory

  - name: Download WMF5 MSU
    win_get_url:
      url: https://go.microsoft.com/fwlink/?linkid=839516
      dest: C:\Temp\Win8.1AndW2K12R2-KB3191564-x64.msu

  - name: Extract PS5 MSU
    win_shell: start-process wusa.exe -Argumentlist "C:\Temp\Win8.1AndW2K12R2-KB3191564-x64.msu /extract:C:\Temp"

  - name: Install PS5 Cab file
    win_shell: dism.exe /Quiet /online /add-package /norestart /Packagepath:C:\Temp\WindowsBlue-KB3191564-x64.cab
    ignore_errors: true

  roles:
  - ad_joined
  - common
  - webserver

#TODO get the localhost meta mof to setup LCM from a kenzo location
# "New-Item -Path 'C:\\DSCSMB' -Type directory -Force",
# "Copy-Item –Path '\\\\kenzoserver\\Software\\kenzo\\DSCSMB\\localhost.meta.mof' –Destination 'C:\\DSCSMB\\'",
# "Set-DscLocalConfigurationManager -Verbose -ComputerName localhost –Path 'C:\\DSCSMB\\'",
