---

- name: set hostname
  win_hostname:
    name: "{{ inventory_hostname_short }}"
  register: res

- name: reboot server after change to hostname
  win_reboot:
    msg: "Changing hostname. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 120
  when: res.reboot_required

#TODO create common function for getting IPv4 address and include here
- name: Create PDC Self Public IP Variable
  raw: "Resolve-DnsName -Name {{groups['primary_domain_controller'][0]}} -Type A -DnsOnly | select -expand IPAddress"
  register: pdc_public_ip

- name: Create RDC Self Public IP Variable
  raw: "Resolve-DnsName -Name {{groups['replica_domain_controller'][0]}} -Type A -DnsOnly | select -expand IPAddress"
  register: rdc_public_ip

- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - "{{ pdc_public_ip.stdout_lines | join }}"
      - "{{ rdc_public_ip.stdout_lines | join }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
    msg: "Joining domain. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 120
  when: domain_joined.reboot_required
